services:

  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    network_mode: "host"
    env_file:
      - ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    network_mode: "host"
    command: redis-server
    ports:
      - "6379:6379"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - ./n8n/.env
    volumes:
      - n8n_data:/home/node/.n8n

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always
    network_mode: "host"
    ports:
      - "8080:8080"
    env_file:
      - ./evolution-api/.env
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

volumes:
  postgres_data:
  n8n_data:
  evolution_store:
  evolution_instances: