
-- Inserção de tipos de transação
INSERT INTO transaction_types (name) VALUES ('income'), ('expense');

-- Inserção de categorias
INSERT INTO categories (name) VALUES
('Alimentação'),
('Transporte'),
('Salário'),
('Moradia'),
('Educação'),
('Saúde'),
('Lazer'),
('Investimentos'),
('Impostos'),
('Seguros'),
('Serviços Públicos'),
('Telefone'),
('Internet'),
('Compras'),
('Roupas'),
('Doações'),
('Viagens'),
('Manutenção do Veículo'),
('Cuidados Pessoais'),
('Animais de Estimação'),
('Assinaturas e Streaming'),
('Empréstimos'),
('Cartão de Crédito'),
('Economias'),
('Presente e Festividades'),
('Consultorias'),
('Materiais de Escritório'),
('Cursos e Treinamentos'),
('Móveis e Decoração'),
('Reparos Domésticos'),
('Multas e Penalidades'),
('Produtos de Limpeza'),
('Farmácia'),
('Aluguel de Equipamentos'),
('Honorários Profissionais'),
('Hobbies'),
('Eventos Culturais'),
('Atividades Esportivas'),
('Tecnologia'),
('Marketing e Publicidade'),
('Serviços de Entrega');
